export const SET_MENU_MOBILE = 'SET_MENU_MOBILE'

export const SET_FORMA_OFFSET_TOP = 'SET_FORMA_OFFSET_TOP'
export const SET_USERS_OFFSET_TOP = 'SET_USERS_OFFSET_TOP'

export const SET_PRELOADER_FORMA_RADIO = 'SET_PRELOADER_FORMA_RADIO'
export const SET_USERS_LOAD = 'SET_USERS_LOAD'
export const SET_PRELOAD_USERS = 'SET_PRELOAD_USERS'
export const SET_LOADING_USERS_SUCCESS= 'SET_LOADING_USERS_SUCESS'

export const SET_RADIO_BUTTONS = 'SET_RADIO_BUTTONS'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USERS = 'SET_USERS'
export const SET_LOADING_USERS = 'SET_LOADING_USERS'

export const SET_FORM_NAME = 'SET_FORM_NAME'
export const SET_FORM_EMAIL = 'SET_FORM_EMAIL'
export const SET_FORM_PHONE_NUMBER = 'SET_FORM_PHONE_NUMBER'
export const SET_FORM_RADIO = 'SET_FORM_RADIO'
export const SET_FORM_IMAGE = 'SET_FORM_IMAGE'
